# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='text',
        ),
    ]
